"""legit-biz-club: the workspace layer of oakridge.

Multi-agent collaboration over a shared artifact, mediated by a project layer.
Built on jig (agent kit) and consumed by kbbl (operator surface).
"""

from legit_biz_club.composition import (
    CompositionMode,
    CompositionPolicy,
    HeterogeneityAxis,
    HeterogeneityCheckFailed,
    HeterogeneityViolation,
    check_heterogeneity,
)
from legit_biz_club.coordination import (
    ConsensusMechanism,
    ConsensusResult,
    DisagreementSurface,
    IncrementalCoordinator,
    IncrementalRunResult,
    JigProposer,
    KCommitsOrStable,
    KCommitsPerAgent,
    Mediator,
    MultiRoundConsensus,
    PickResult,
    ProjectCoordinator,
    ProjectRunResult,
    Proposal,
    ProposalOutcome,
    ProposalResult,
    Proposer,
    ProposerOutputParseError,
    RoundBudgetPolicy,
    RoundOutcome,
    SingleRoundConsensus,
    StableOrderingByAgentId,
    StringEqualConvergence,
    TerminationPolicy,
    WorkspaceEventEmitter,
    compute_version,
    make_proposers,
)
from legit_biz_club.core import (
    Agent,
    Artifact,
    ArtifactType,
    Brief,
    CoordinationProtocol,
    Enrollment,
    InvalidTransitionError,
    Project,
    ProjectState,
    transition_to,
)
from legit_biz_club.memory import (
    CommitObservation,
    CommitResult,
    MemoryCommitter,
    OperatorConfidence,
    PeerContextLoader,
    make_sqlite_observation_loader,
)

__all__ = [
    "Agent",
    "Artifact",
    "ArtifactType",
    "Brief",
    "CommitObservation",
    "CommitResult",
    "CompositionMode",
    "CompositionPolicy",
    "ConsensusMechanism",
    "ConsensusResult",
    "CoordinationProtocol",
    "DisagreementSurface",
    "Enrollment",
    "HeterogeneityAxis",
    "HeterogeneityCheckFailed",
    "HeterogeneityViolation",
    "IncrementalCoordinator",
    "IncrementalRunResult",
    "InvalidTransitionError",
    "JigProposer",
    "KCommitsOrStable",
    "KCommitsPerAgent",
    "Mediator",
    "MemoryCommitter",
    "MultiRoundConsensus",
    "OperatorConfidence",
    "PeerContextLoader",
    "PickResult",
    "Project",
    "ProjectCoordinator",
    "ProjectRunResult",
    "ProjectState",
    "Proposal",
    "ProposalOutcome",
    "ProposalResult",
    "Proposer",
    "ProposerOutputParseError",
    "RoundBudgetPolicy",
    "RoundOutcome",
    "SingleRoundConsensus",
    "StableOrderingByAgentId",
    "StringEqualConvergence",
    "TerminationPolicy",
    "WorkspaceEventEmitter",
    "check_heterogeneity",
    "compute_version",
    "make_proposers",
    "make_sqlite_observation_loader",
    "transition_to",
]
